# Generated by Django 5.1.6 on 2026-03-18 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOST', 'LOST'), ('FOUND', 'FOUND')], max_length=10)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(max_length=240)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('incident_at', models.DateTimeField()),
                ('visibility_scope', models.CharField(default='nearby', max_length=32)),
                ('verification_status', models.CharField(choices=[('under-review', 'under-review'), ('verified', 'verified'), ('rejected', 'rejected')], default='under-review', max_length=32)),
                ('authenticity_detail', models.TextField()),
                ('feature_data', models.JSONField(blank=True, default=dict)),
                ('ai_suggested_category', models.CharField(blank=True, max_length=64)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('details_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('current_state', models.CharField(default='open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=10)),
                ('media_file', models.FileField(upload_to='items/')),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_auto_notified', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='items.item')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='items.item')),
            ],
            options={
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
