import type { PendingItem, VerifiedItem, AppUser, MetricsSummary } from "../types";

export const mockMetrics: MetricsSummary = {
  totalReports: 142,
  pendingApprovals: 5,
  verifiedItems: 97,
  totalUsers: 312,
  urgentCases: 2,
};

export const mockPendingItems: PendingItem[] = [
  {
    id: "p-001",
    title: "Missing Red Backpack",
    status: "LOST",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    location: "Rajshahi University Gate 2",
    submittedBy: "ananya.s",
    submittedAt: "2026-03-17T10:30:00Z",
    description: "Red backpack left near library entrance after evening classes.",
    authenticityDetail: "Red embroidered logo on the back pocket",
    category: "Bags",
    isUrgent: true,
  },
  {
    id: "p-002",
    title: "Lost Smartwatch",
    status: "LOST",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    location: "Zero Point Food Plaza",
    submittedBy: "rifat_89",
    submittedAt: "2026-03-17T09:15:00Z",
    description: "Black smartwatch with cracked edge, last synced at 2:10 PM.",
    authenticityDetail: "Serial: SW2024987654",
    category: "Electronics",
    isUrgent: false,
  },
  {
    id: "p-003",
    title: "Found Blue Wallet",
    status: "FOUND",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
    location: "Dhaka Park Street",
    submittedBy: "omar.finds",
    submittedAt: "2026-03-17T08:45:00Z",
    description: "Blue leather wallet found near the park bench, contains some cards.",
    authenticityDetail: "Has a small 'K' monogram embossed inside",
    category: "Bags",
    isUrgent: false,
  },
  {
    id: "p-004",
    title: "Lost Cat – Mimo",
    status: "LOST",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=600&q=80",
    location: "Shalbagan Residential Area",
    submittedBy: "sadia.home",
    submittedAt: "2026-03-16T22:00:00Z",
    description: "White and ginger cat, blue collar with bell, very friendly.",
    authenticityDetail: "Small birthmark on the right ear",
    category: "Pets",
    isUrgent: true,
  },
  {
    id: "p-005",
    title: "Found iPhone 15",
    status: "FOUND",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80",
    location: "Gulshan 2 Metro Station",
    submittedBy: "karim.dhaka",
    submittedAt: "2026-03-17T11:00:00Z",
    description: "Black iPhone 15 found on the platform bench.",
    authenticityDetail: "Cracked back cover on the bottom-left corner",
    category: "Electronics",
    isUrgent: false,
  },
];

export const mockVerifiedItems: VerifiedItem[] = [
  {
    id: "v-001",
    title: "Returned: Black Laptop Bag",
    status: "FOUND",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&w=600&q=80",
    location: "BUET Campus",
    submittedBy: "help.finder",
    approvedAt: "2026-03-16T14:00:00Z",
    category: "Bags",
  },
  {
    id: "v-002",
    title: "Lost Keys – Toyota",
    status: "LOST",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80",
    location: "Dhanmondi Lake",
    submittedBy: "kamal.hossain",
    approvedAt: "2026-03-16T10:20:00Z",
    category: "Keys",
  },
  {
    id: "v-003",
    title: "Found Passport",
    status: "FOUND",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1619468129361-605ebea04b44?auto=format&fit=crop&w=600&q=80",
    location: "Hazrat Shahjalal Airport",
    submittedBy: "honest_citizen",
    approvedAt: "2026-03-15T18:30:00Z",
    category: "Documents",
  },
  {
    id: "v-004",
    title: "Lost Dog – Bruno",
    status: "LOST",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=600&q=80",
    location: "Uttara Sector 11",
    submittedBy: "parveen.k",
    approvedAt: "2026-03-14T09:00:00Z",
    category: "Pets",
  },
];

export const mockUsers: AppUser[] = [
  {
    id: "u-001",
    name: "Ananya Sharma",
    email: "ananya.s@mail.com",
    trustLevel: "verified",
    itemsReported: 4,
    isSuspended: false,
    joinedAt: "2026-01-10",
  },
  {
    id: "u-002",
    name: "Rifat Hossain",
    email: "rifat_89@mail.com",
    trustLevel: "new",
    itemsReported: 1,
    isSuspended: false,
    joinedAt: "2026-03-15",
  },
  {
    id: "u-003",
    name: "Sadia Rahman",
    email: "sadia.home@mail.com",
    trustLevel: "trusted",
    itemsReported: 12,
    isSuspended: false,
    joinedAt: "2025-11-02",
  },
  {
    id: "u-004",
    name: "Omar Faruk",
    email: "omar.finds@mail.com",
    trustLevel: "verified",
    itemsReported: 7,
    isSuspended: false,
    joinedAt: "2025-12-20",
  },
  {
    id: "u-005",
    name: "Karim Ahmed",
    email: "karim.dhaka@mail.com",
    trustLevel: "new",
    itemsReported: 2,
    isSuspended: true,
    joinedAt: "2026-02-14",
  },
];
